[build]
  command = "npm install"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"  # Folder Edge Functions

[[edge_functions]]  # Deklarasi path untuk Edge Function
  function = "gambar"  # Nama file tanpa .js
  path = "/gambar"     # Path yang harus dipanggil: /gambar

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[build.environment]
  NODE_VERSION = "22"
