[build]
  command = "npm install"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  path = "/gambar"
  function = "gambar"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[build.environment]
  NODE_VERSION = "22"
